"""Init models

Revision ID: 159aba84da2d
Revises: 7e4389492d90
Create Date: 2024-10-26 14:30:55.463065

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159aba84da2d'
down_revision: Union[str, None] = '7e4389492d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('living_building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_db_house_id', sa.Integer(), nullable=True),
    sa.Column('parent_territory_id', sa.Integer(), nullable=True),
    sa.Column('center', geoalchemy2.types.Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_db_house_id')
    )
    op.create_table('living_building_population',
    sa.Column('living_building_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('forecast_type', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['living_building_id'], ['living_building.id'], ),
    sa.PrimaryKeyConstraint('living_building_id', 'year', 'forecast_type'),
    sa.UniqueConstraint('living_building_id', 'year', 'forecast_type', name='_building_year_type_uc'),
    postgresql_partition_by='RANGE (year, forecast_type)'
    )
    op.create_index(op.f('ix_living_building_population_forecast_type'), 'living_building_population', ['forecast_type'], unique=False)
    op.create_index(op.f('ix_living_building_population_living_building_id'), 'living_building_population', ['living_building_id'], unique=False)
    op.create_index(op.f('ix_living_building_population_year'), 'living_building_population', ['year'], unique=False)
    op.create_table('living_building_population_distribution',
    sa.Column('living_building_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('forecast_type', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('age', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['living_building_id'], ['living_building.id'], ),
    sa.PrimaryKeyConstraint('living_building_id', 'age', 'gender', 'year', 'forecast_type'),
    sa.UniqueConstraint('living_building_id', 'year', 'forecast_type', 'gender', 'age', name='_building_year_type_gender_age_uc'),
    postgresql_partition_by='RANGE (year, forecast_type)'
    )
    op.create_index(op.f('ix_living_building_population_distribution_age'), 'living_building_population_distribution', ['age'], unique=False)
    op.create_index(op.f('ix_living_building_population_distribution_forecast_type'), 'living_building_population_distribution', ['forecast_type'], unique=False)
    op.create_index(op.f('ix_living_building_population_distribution_gender'), 'living_building_population_distribution', ['gender'], unique=False)
    op.create_index(op.f('ix_living_building_population_distribution_living_building_id'), 'living_building_population_distribution', ['living_building_id'], unique=False)
    op.create_index(op.f('ix_living_building_population_distribution_year'), 'living_building_population_distribution', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_living_building_population_distribution_year'), table_name='living_building_population_distribution')
    op.drop_index(op.f('ix_living_building_population_distribution_living_building_id'), table_name='living_building_population_distribution')
    op.drop_index(op.f('ix_living_building_population_distribution_gender'), table_name='living_building_population_distribution')
    op.drop_index(op.f('ix_living_building_population_distribution_forecast_type'), table_name='living_building_population_distribution')
    op.drop_index(op.f('ix_living_building_population_distribution_age'), table_name='living_building_population_distribution')
    op.drop_table('living_building_population_distribution')
    op.drop_index(op.f('ix_living_building_population_year'), table_name='living_building_population')
    op.drop_index(op.f('ix_living_building_population_living_building_id'), table_name='living_building_population')
    op.drop_index(op.f('ix_living_building_population_forecast_type'), table_name='living_building_population')
    op.drop_table('living_building_population')
    op.drop_table('living_building')
    # ### end Alembic commands ###
