"""upd models

Revision ID: 903ccaf3a248
Revises: 5041f4806a3f
Create Date: 2024-10-23 23:25:14.733956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903ccaf3a248'
down_revision: Union[str, None] = '5041f4806a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('_building_year_type_uc', 'living_building_population', ['living_building_id', 'year', 'forecast_type'])
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('_building_year_type_uc', 'living_building_population', type_='unique')
    # ### end Alembic commands ###
    pass
